# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import SC_communication_gRPC_pb2 as SC__communication__gRPC__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in SC_communication_gRPC_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SC_communication_gRPCStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMessage = channel.unary_unary(
                '/sc_communication_gRPC.SC_communication_gRPC/SendMessage',
                request_serializer=SC__communication__gRPC__pb2.MessageRequest.SerializeToString,
                response_deserializer=SC__communication__gRPC__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.SubscribeMessages = channel.unary_stream(
                '/sc_communication_gRPC.SC_communication_gRPC/SubscribeMessages',
                request_serializer=SC__communication__gRPC__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=SC__communication__gRPC__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.SubscribeUpdates = channel.unary_stream(
                '/sc_communication_gRPC.SC_communication_gRPC/SubscribeUpdates',
                request_serializer=SC__communication__gRPC__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=SC__communication__gRPC__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.SendImage = channel.unary_stream(
                '/sc_communication_gRPC.SC_communication_gRPC/SendImage',
                request_serializer=SC__communication__gRPC__pb2.ImageRequest.SerializeToString,
                response_deserializer=SC__communication__gRPC__pb2.ImageResponse.FromString,
                _registered_method=True)
        self.CommandMessage = channel.unary_stream(
                '/sc_communication_gRPC.SC_communication_gRPC/CommandMessage',
                request_serializer=SC__communication__gRPC__pb2.MessageRequest.SerializeToString,
                response_deserializer=SC__communication__gRPC__pb2.MsgResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/sc_communication_gRPC.SC_communication_gRPC/Heartbeat',
                request_serializer=SC__communication__gRPC__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=SC__communication__gRPC__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.ExecuteCameraCommand = channel.unary_unary(
                '/sc_communication_gRPC.SC_communication_gRPC/ExecuteCameraCommand',
                request_serializer=SC__communication__gRPC__pb2.CommandRequest.SerializeToString,
                response_deserializer=SC__communication__gRPC__pb2.CommandReply.FromString,
                _registered_method=True)
        self.QueryCameraState = channel.unary_unary(
                '/sc_communication_gRPC.SC_communication_gRPC/QueryCameraState',
                request_serializer=SC__communication__gRPC__pb2.QueryRequest.SerializeToString,
                response_deserializer=SC__communication__gRPC__pb2.QueryReply.FromString,
                _registered_method=True)


class SC_communication_gRPCServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommandMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCameraCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryCameraState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SC_communication_gRPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=SC__communication__gRPC__pb2.MessageRequest.FromString,
                    response_serializer=SC__communication__gRPC__pb2.MessageResponse.SerializeToString,
            ),
            'SubscribeMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeMessages,
                    request_deserializer=SC__communication__gRPC__pb2.SubscribeRequest.FromString,
                    response_serializer=SC__communication__gRPC__pb2.MessageResponse.SerializeToString,
            ),
            'SubscribeUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeUpdates,
                    request_deserializer=SC__communication__gRPC__pb2.SubscribeRequest.FromString,
                    response_serializer=SC__communication__gRPC__pb2.MessageResponse.SerializeToString,
            ),
            'SendImage': grpc.unary_stream_rpc_method_handler(
                    servicer.SendImage,
                    request_deserializer=SC__communication__gRPC__pb2.ImageRequest.FromString,
                    response_serializer=SC__communication__gRPC__pb2.ImageResponse.SerializeToString,
            ),
            'CommandMessage': grpc.unary_stream_rpc_method_handler(
                    servicer.CommandMessage,
                    request_deserializer=SC__communication__gRPC__pb2.MessageRequest.FromString,
                    response_serializer=SC__communication__gRPC__pb2.MsgResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=SC__communication__gRPC__pb2.HeartbeatRequest.FromString,
                    response_serializer=SC__communication__gRPC__pb2.HeartbeatResponse.SerializeToString,
            ),
            'ExecuteCameraCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCameraCommand,
                    request_deserializer=SC__communication__gRPC__pb2.CommandRequest.FromString,
                    response_serializer=SC__communication__gRPC__pb2.CommandReply.SerializeToString,
            ),
            'QueryCameraState': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryCameraState,
                    request_deserializer=SC__communication__gRPC__pb2.QueryRequest.FromString,
                    response_serializer=SC__communication__gRPC__pb2.QueryReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sc_communication_gRPC.SC_communication_gRPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sc_communication_gRPC.SC_communication_gRPC', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SC_communication_gRPC(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sc_communication_gRPC.SC_communication_gRPC/SendMessage',
            SC__communication__gRPC__pb2.MessageRequest.SerializeToString,
            SC__communication__gRPC__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sc_communication_gRPC.SC_communication_gRPC/SubscribeMessages',
            SC__communication__gRPC__pb2.SubscribeRequest.SerializeToString,
            SC__communication__gRPC__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sc_communication_gRPC.SC_communication_gRPC/SubscribeUpdates',
            SC__communication__gRPC__pb2.SubscribeRequest.SerializeToString,
            SC__communication__gRPC__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sc_communication_gRPC.SC_communication_gRPC/SendImage',
            SC__communication__gRPC__pb2.ImageRequest.SerializeToString,
            SC__communication__gRPC__pb2.ImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommandMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sc_communication_gRPC.SC_communication_gRPC/CommandMessage',
            SC__communication__gRPC__pb2.MessageRequest.SerializeToString,
            SC__communication__gRPC__pb2.MsgResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sc_communication_gRPC.SC_communication_gRPC/Heartbeat',
            SC__communication__gRPC__pb2.HeartbeatRequest.SerializeToString,
            SC__communication__gRPC__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCameraCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sc_communication_gRPC.SC_communication_gRPC/ExecuteCameraCommand',
            SC__communication__gRPC__pb2.CommandRequest.SerializeToString,
            SC__communication__gRPC__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryCameraState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sc_communication_gRPC.SC_communication_gRPC/QueryCameraState',
            SC__communication__gRPC__pb2.QueryRequest.SerializeToString,
            SC__communication__gRPC__pb2.QueryReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
